/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Keyring(props) {
  const { nodes } = useGLTF("/keyring.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={nodes.Circle.material}
      />
      <meshBasicMaterial color={"white"} />
    </group>
  );
}

useGLTF.preload("/keyring.glb");
